# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20160505_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='user',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
